name: linting

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    name: All
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.x"
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@434f5f3816b358fe468fa83dcba62d794e7fe04b # 2021.1 (v0.2.0)
      - name: Check that go.mod is tidy
        uses: protocol/multiple-go-modules@v1.0
        with:
          run: |
            go mod tidy
            if [[ -n $(git ls-files --other --exclude-standard --directory -- go.sum) ]]; then
              echo "go.sum was added by go mod tidy"
              exit 1
            fi
            git diff --exit-code -- go.sum go.mod
      - name: gofmt
        run: |
          out=$(gofmt -s -l .)
          if [[ -n "$out" ]]; then
            echo $out | awk '{print "::error file=" $0 ",line=0,col=0::File is not gofmt-ed."}'
            exit 1
          fi
      - name: go vet
        uses: protocol/multiple-go-modules@v1.0
        with:
          run: go vet ./...
      - name: staticcheck
        uses: protocol/multiple-go-modules@v1.0
        with:
          run: |
            set -o pipefail
            staticcheck ./... | sed -e 's@\(.*\)\.go@./\1.go@g'
